version:            "3.2"

services:
  anki-service:
    container_name: "anki"
    restart:        always

    # volumes:
    #   - ./:/apiapp
    #   - /apiapp/node_modules
    build:          .
    image:          "anki"
    # image:          "923942996254.dkr.ecr.ap-northeast-1.amazonaws.com/anki:latest"
    ports:
      - "8090:80"
      - "9145:9145"
    # networks:
    #   - backend
    # networks:
    #   app_net:
    #     ipv4_address: 172.16.238.10

# networks:
#   ps-bridge:
#     driver: bridge
#     # enable_ipv6: true
#     ipam:
#       driver: default
#       config:
#       - subnet: 10.0.0.0/24
# networks:
#   app_net:
#     driver: bridge
#     enable_ipv6: true
#     ipam:
#       driver: default
#       config:
#       -
#         subnet: 172.16.238.0/24
#       -
#         subnet: 2001:3984:3989::/64

# networks:
#   ps-bridge:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#       -
#         subnet: 10.0.0.0/24
