version: 2
general:
  branches:
    only:
      - master # list of branches to build
      - wip

# defaults: &defaults
#   working_directory: ~/repo # /root/project
#   docker:
#     - image: circleci/ruby:2.4.2-jessie-node-browsers
#       environment:
#         PGHOST: 127.0.0.1
#         PGUSER: loot_user
#         RAILS_ENV: test
#     - image: circleci/postgres:9.5-alpine
#       environment:
#         POSTGRES_USER: loot_user
#         POSTGRES_DB: loot_test
#         POSTGRES_PASSWORD: ""
#### use <<: *defaults under job to use default

jobs:
  init:
    # working_directory: ~/repo
    docker:
      - image: $DOCKER_ADD/js-base-image:latest

    # working_directory: ~/repo # Needed to build docker as you use . # Default is /root/project

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-  # fallback to using the latest cache if no exact match is found
      - run: npm ci --production # Have to run it again as the image does not seem to have node_module when used as a base image..
      - run: npx snyk test --severity-threshold=high
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

  test:
    # working_directory: /js-base-image # default is Default is /root/project
    docker:
      - image: $DOCKER_ADD/js-base-image:latest
    steps:
      - checkout
      - run:
          name: Copy project dir under js-base-image for testing
          command: mkdir -p /js-base-image/packages/project && cp -r . /js-base-image/packages/project/
      - run:
          name: Download code climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > /root/project/cc-test-reporter
            chmod +x /root/project/cc-test-reporter
      - run:
          name: Run test and save coverage result
          command: |
            # notify Code Climate of a pending test report using `before-build`
            /root/project/cc-test-reporter before-build
            cd /js-base-image/packages/project && npm run test:ci
            # upload test report to Code Climate using `after-build`
            if [ -z "$NOT_DEPLOY_COV_REPORT" ]; then
              cd /js-base-image/ && /root/project/cc-test-reporter after-build --coverage-input-type lcov --exit-code $? # Providing this will prevent sending test coverage results for failed tests.
            fi
      - store_test_results:
          path: /js-base-image/coverage/
      - store_artifacts:
          path: /js-base-image/coverage/
      # - run: ls -al /js-base-image/coverage/

  test:e2e:
    docker:
      - image: $DOCKER_ADD/js-base-image:latest
      # - image: testcafe/testcafe
    steps:
      - checkout
      # - run:
      #     name: Copy project dir under js-base-image for testing
      #     command: mkdir -p /js-base-image/packages/project && cp -r . /js-base-image/packages/project/
      # - run: cd /js-base-image/packages/project && npm ci --production # for babel-node

      # - run: pwd
      # - run: ls -al /root/project/test-e2e

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Docker login
          command: eval "$(aws ecr get-login --no-include-email --region ap-northeast-1)"

      - run:
          name: build and run docker image
          command: |
            docker build -t $REPO_NAME .
            docker network create -d bridge --subnet 10.0.0.1/24 docker-bridge
            docker run --network docker-bridge --ip 10.0.0.10 $REPO_NAME # Fixed at 10.0.0.10
            cd /js-base-image/packages/project && npm run test:e2e:docker:ci

      # - run: docker system info
      # - run: docker run -v /root/project/test-e2e:/tests -it testcafe/testcafe 'chromium:headless --no-sandbox' /tests

  push-deploy:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: sudo apt-get install python-dev
      - run: sudo pip install awscli
      - run:
          name: Docker login
          command: eval "$(aws ecr get-login --no-include-email --region ap-northeast-1)"

      - run:
          name: Building the image and push to ecr
          command: | # Need | to run line by line
            TAG=latest
            docker build -t $REPO_NAME .
            docker tag $REPO_NAME:$TAG $DOCKER_ADD/$REPO_NAME:$TAG
            docker push $DOCKER_ADD/$REPO_NAME:$TAG

      - run:
          name: Logging into ec2 and update the k8s
          command: |
            # environment var wont work because it is in an embedded script
            if [ -z "$NOT_DEPLOY_K8S" ]; then # Not set is -z, set is -n
              ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "kubectl delete -f k8s/'${REPO_K8S_FOLDER}'/'${REPO_NAME}'.yml && kubectl create -f k8s/'${REPO_K8S_FOLDER}'/'${REPO_NAME}'.yml" # If get long, get a file
            fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - test:e2e
      # - init
      # - test:
      #     requires:
      #       - init
      # - push-deploy:
      #     requires:
      #       - test
