version: 2
general:
  branches:
    only:
      - master # list of branches to build

  working_directory: ~/repo # Needed to build docker as you use .

jobs:
  preparation:
    docker:
      - image: circleci/node:8.11
      # - image: circleci/python:3.7

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: yarn test

  push-deploy:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout

      # You should be able to cache this too..
      - run: sudo apt-get install python-dev
      - run: sudo pip install awscli

      # Building Docker Image, Login and Push
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: docker login
          command: eval "$(aws ecr get-login --no-include-email --region ap-northeast-1)" # Exec output of command
            # docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_ADD

      - run:
          name: Building the image and push to ecr
          command: | # Need | to run line by line
            TAG=latest
            docker build -t $REPO_NAME .
            docker tag $REPO_NAME:$TAG $DOCKER_ADD/$REPO_NAME:$TAG
            docker push $DOCKER_ADD/$REPO_NAME:$TAG

      - run:
          name: Logging into ec2 and update the k8s
          command: |
            # environment var wont work because it is in an embedded script
            if [ -z "$PUSH_ONLY" ]; then # Not set is -z, set is -n
              ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST 'kubectl delete -f k8s/frontend/hourblock.yml && kubectl create -f k8s/frontend/hourblock.yml' # If get long, get a file
            fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - preparation
      - push-deploy
      # - deploy
